In [ ]:
from pycaret.regression import *
import pandas as pd
from sklearn import metrics
from scipy.stats import pearsonr
import matplotlib.pyplot as plt

In [3]:
df_fa = pd.read_csv('/home/syb/Code/coupling/python/jupyter/file/SDI_sub/sc_mode_1.csv')
df_md = pd.read_csv('/home/syb/Code/coupling/python/jupyter/file/SDI_sub/sc_mode_2.csv')
df_num = pd.read_csv('/home/syb/Code/coupling/python/jupyter/file/SDI_sub/sc_mode_3.csv')
df_label = pd.read_csv('/home/syb/Code/coupling/python/jupyter/file/sc_mode_label.csv')
df_info = pd.read_csv('/home/syb/Code/coupling/python/jupyter/file/sc_mode_info.csv')
df_mode= [df_fa,df_md,df_num]

In [8]:
df_sc1= pd.concat([df_mode[mode],df_info],join="outer",axis=1)
df = df_sc1.sample(frac=1).reset_index(drop=True)
df_test = df[df['center']== center].drop(axis=1,columns=['center','label'])
df_train = df[df['center'] != center].drop(axis=1,columns=['center','label'])
df_all = df.drop(axis=1,columns=['center','label'])
s = setup(df_train, target = 'mmse')
best = compare_models()
#pre_re = predict_model(best, df_test)

In [9]:
pre_re = predict_model(best, df_test)

In [4]:


r2_re = []
y_pred_3 = []
y_true_3 = []

r_list = []

#计算三种模态各个的分类性能
for mode in range(3):
    y_pred_mode = []
    y_true_mode = []
    #fig, ax = plt.subplots(figsize=(3, 3))
    #把fa和info合并成一个表格
    df_sc1= pd.concat([df_mode[mode],df_info],join="outer",axis=1)
    for i in range(7):
        center = i+1
        df = df_sc1.sample(frac=1).reset_index(drop=True)
        #df = df[df['label'] !=2]
        #df = df['label'].replace(3,0)
        
        #df.loc[df['label']==3,'label'] = 0
        df_test = df[df['center']== center].drop(axis=1,columns=['center','label'])
        df_train = df[df['center'] != center].drop(axis=1,columns=['center','label'])
        
        y_test = df_test['mmse'].values
        y_train = df_train['mmse'].values
        x_test = df_test.drop(axis=1,columns=['mmse']).values
        x_train = df_train.drop(axis=1,columns=['mmse']).values

        s = setup(df_train, target = 'mmse')
        best = compare_models()
        y_pred = predict_model(best, df_test)

        y_pred_mode.extend(y_pred)
        y_true_mode.extend(y_test)
        r2_re.append(pearsonr(y_pred,y_test)[0])

    y_pred_3.append(y_pred_mode)
    y_true_3.append(y_true_mode)
    r_list.append(pearsonr(y_pred_mode,y_true_mode)[0])

    fig, ax = plt.subplots(figsize=(8, 8))
    plt.scatter(y_true_mode,y_pred_mode)
    plt.xlim([0,35])
    plt.ylim([0,35])
    plt.show()

Initiated  . . . . . . . . . . . . . . . . . .           18:51:46
Status     . . . . . . . . . . . . . . . . . .   Fitting 10 Folds
Estimator  . . . . . . . . . . . . . . . . . .  Linear Regression

Initiated  . . . . . . . . . . . . . . . . . .           18:52:12
Status     . . . . . . . . . . . . . . . . . .   Fitting 10 Folds
Estimator  . . . . . . . . . . . . . . . . . .  Linear Regression

Initiated  . . . . . . . . . . . . . . . . . .           18:52:28
Status     . . . . . . . . . . . . . . . . . .   Fitting 10 Folds
Estimator  . . . . . . . . . . . . . . . . . .  Linear Regression

Initiated  . . . . . . . . . . . . . . . . . .           18:52:43
Status     . . . . . . . . . . . . . . . . . .   Fitting 10 Folds
Estimator  . . . . . . . . . . . . . . . . . .  Linear Regression

Initiated  . . . . . . . . . . . . . . . . . .           18:52:58
Status     . . . . . . . . . . . . . . . . . .   Fitting 10 Folds
Estimator  . . . . . . . . . . . . . . . . . .  Linear Regression

In [4]:
s = setup(df_fa_1, target = 'label_1')

In [5]:

best = compare_models()

In [6]:
evaluate_model(best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [7]:
predict_model(best)

,a_1,a_2,a_3,a_4,a_5,a_6,a_7,a_8,a_9,a_10,...,a_239,a_240,a_241,a_242,a_243,a_244,a_245,a_246,label_1,prediction_label
555,1.027020,0.827975,0.889371,0.674521,0.563307,0.778676,0.761162,0.866649,0.666834,0.554440,...,0.975175,1.469561,2.145775,1.717200,1.952389,1.749354,1.000618,1.229090,30,27.0
556,0.375951,0.376068,0.851000,1.408882,0.457453,0.465837,0.647231,0.612324,0.361296,0.559597,...,1.201799,1.438294,1.351304,2.093652,1.443091,2.375130,1.172786,1.396079,22,14.2
557,0.952428,0.744823,1.238560,1.302209,1.134831,0.925659,0.705468,0.670363,0.505072,0.460603,...,0.704849,0.754672,1.453609,1.188720,1.423825,1.256868,0.545407,0.738799,21,20.2
558,0.776989,0.541676,0.954184,0.852591,0.707254,0.392883,1.104540,1.291562,0.536519,0.753217,...,1.247475,1.329149,0.695895,1.462840,0.930384,1.544271,1.323627,1.335808,30,28.4
559,0.853878,1.024525,0.874184,1.165736,0.601319,0.681928,0.941514,0.889317,0.811851,0.748135,...,1.301549,1.547782,1.523154,1.477116,1.205080,1.439117,1.517102,1.435745,16,21.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
788,0.477968,0.449695,0.889562,1.013843,0.641781,0.475989,0.503655,0.632482,0.451209,0.368669,...,1.131019,1.054868,0.847610,1.263937,0.781815,1.692911,1.074921,1.103040,30,28.6
789,0.676074,0.632043,0.952571,0.783932,0.615281,0.426732,0.823901,0.740005,0.685313,0.726525,...,0.903869,0.876093,1.037898,1.292572,1.045958,1.078414,1.065161,0.666848,14,23.0
790,0.868023,0.730633,0.857869,0.858808,0.471105,0.453034,0.924687,1.016371,0.593918,0.696366,...,1.938573,1.560841,1.298989,1.266045,1.190910,1.714411,1.731924,1.666394,30,28.0
791,0.438143,0.393823,0.467920,0.832138,0.408676,0.540801,0.813065,0.781616,0.721571,0.431599,...,1.966352,1.482548,1.052683,1.456750,1.344642,2.224171,2.036813,2.294364,24,18.0
792,0.709490,0.555105,0.689418,0.574038,0.607128,0.736203,0.706595,0.520434,0.527907,0.685949,...,1.061975,0.872296,1.386178,1.134269,1.641853,1.144003,1.223525,0.864305,22,9.4